= Latin-2-Assignments
:toc: left
:toclevels: 3
:sectids:
:sectlinks:
:sectanchors:
:sectnums:
:sectnumlevels: 2
:ch7voc: https://drive.google.com/file/d/1OpHGZ-rP5bunDBuG6Z92R09_3ZNoa2gN/view?usp=share_link[Chapter 7 Vocabulary] https://drive.google.com/file/d/1OqWMBNDcFYhdpNPOOf1KwIVxZhN-EOlB/view?usp=sharing[Chapter 1 Homework]


== 1st Quarter
=== Module 1 -- Review 1
==== Week 1
//tag::Week-1[]
//tag::Weekly-Overview-1[]
July 22-26

There is no "Launch Work."
//end::Weekly-Overview-1[]
//end::Week-1[]

==== Week 2
//tag::Week-2
//tag::Weekly-Overview-2[]
July 29-Aug 2

There is no "Launch Work."
//end::Weekly-Overview-2[]
//end::Week-2[]

==== Week 3
//tag::Week-3[]
Chapters 1-7

//tag::Weekly-Overview-3[]
Aug 5-9

We will study chapter 1.

We will start studying chapter 2.

//end::Weekly-Overview-3[]
//tag::Assignment-001[]
===== Monday, August 5, 2024
No work

//end::Assignment-001[]
//tag::Assignment-002[]
===== Tuesday, August 6, 2024
We covered the syllabus and discussed homework for the week.

We started the homework for chapter 1.

https://drive.google.com/file/d/1OqWMBNDcFYhdpNPOOf1KwIVxZhN-EOlB/view?usp=sharing[Chapter 1 Homework]

//end::Assignment-002[]
//tag::Assignment-003[]
===== Wednesday, August 7, 2024
Finish translating the sentences for chapter 1.

Begin studying the verb endings from chapter 1.

Begin reviewing the vocabulary for chapters 1 and 2.

https://drive.google.com/file/d/1A70nrAUy-A_WOe77dW66EiYtrfc0_oGE/view?usp=share_link[Chapter 1 and 2 Voabulary]

 
//end::Assignment-003[]
//tag::Assignment-004[]
===== Thursday, August 8, 2024
Upload the homework for chapter 1.

Study the verb endings from chapter 1.

Study the vocabulary for chapters 1 and 2.

https://drive.google.com/file/d/1A70nrAUy-A_WOe77dW66EiYtrfc0_oGE/view?usp=share_link[Chapter 1 and 2 Vocabulary]


//end::Assignment-004[]
//tag::Assignment-005[]
===== Friday, August 9, 2024
We will learn about first declension nouns and adjectives.

We will translate most of the homework for chapter 2.

https://drive.google.com/file/d/1OladSAbdcO7Wsa3xBsJEqa_QADbUAKuy/view?usp=sharing[Chapter 2 Homework]

//end::Assignment-005[]

//end::Week-3[]


==== Week 4
//tag::Week-4[]
Chapters 8-12

//tag::Weekly-Overview-4[]
We will learn about second declension masculine nouns and adjectives as well as apposition.

//end::Weekly-Overview-4[]
//tag::Assignment-006[]
===== Monday, August 12, 2024

If the links do not work, try right-clicking them and opening them in a new tab.

Upload the homework for chapter 2.
https://drive.google.com/file/d/1OladSAbdcO7Wsa3xBsJEqa_QADbUAKuy/view?usp=sharing[Chapter 2 Homework]

Study the verb endings from chapter 1.

Study the noun endings from chapter 2.

Study the vocabulary for chapters 1 and 2.
https://drive.google.com/file/d/1A70nrAUy-A_WOe77dW66EiYtrfc0_oGE/view?usp=share_link[Chapter 1 and 2 Vocabulary]

//end::Assignment-006[]

//tag::Quiz-01[]
We will have a quiz over the vocabulary, grammar, and translations from chapters 1 and 2.

//end::Quiz-01[]
//tag::Assignment-007[]
===== Tuesday, August 13, 2024
We will learn about second declension masculine nouns and adjectives as well as apposition.

We will translate most of the homework for chapter 3.

https://drive.google.com/file/d/1OmGNkAhGTdaLhmG7YTlfBvXSyW4MTdZG/view?usp=sharing[Chapter 3 Homework]

//end::Assignment-007[]
//tag::Assignment-008[]
===== Wednesday, August 14, 2024

Finish your chapter 3 translations. 
https://drive.google.com/file/d/1OmGNkAhGTdaLhmG7YTlfBvXSyW4MTdZG/view?usp=sharing[Chapter 3 Homework]

Study you vocabulary for chapter 3.
https://drive.google.com/file/d/1OphxduV7WujulzLsxwIeXoXO_XWuT71U/view?usp=share_link[Chapter 3 Vocabulary]

//end::Assignment-008[]
//tag::Assignment-009[]
===== Thursday, August 15, 2024

Upload you translations for chapter 3.
https://drive.google.com/file/d/1OmGNkAhGTdaLhmG7YTlfBvXSyW4MTdZG/view?usp=sharing[Chapter 3 Homework]

Study you vocabulary for chapter 3.
https://drive.google.com/file/d/1OphxduV7WujulzLsxwIeXoXO_XWuT71U/view?usp=share_link[Chapter 3 Vocabulary]

Review past vocabulary.
https://drive.google.com/file/d/1A70nrAUy-A_WOe77dW66EiYtrfc0_oGE/view?usp=share_link[Chapter 1 and 2 Vocabulary]


//end::Assignment-009[]
//tag::Assignment-010[]
===== Friday, August 16, 2024
We will translate a story in class.

https://drive.google.com/file/d/1OmV19I2sgJsoaPeLTGu82G-Pj0mQygo_/view?usp=sharing[Chapter 3 Story]

//end::Assignment-010[]
//tag::Quiz-02[]
We will have a quiz over the vocabulary, grammar, and translations from chapter 3

https://drive.google.com/file/d/1OmGNkAhGTdaLhmG7YTlfBvXSyW4MTdZG/view?usp=sharing[Chapter 3 Homework]

Study you vocabulary for chapter 3.
https://drive.google.com/file/d/1OphxduV7WujulzLsxwIeXoXO_XWuT71U/view?usp=share_link[Chapter 3 Vocabulary]

//end::Quiz-02[]
//end::Week-4[]

==== Week 5
//tag::Week-5[]
Chapters 13-17

//tag::Weekly-Overview-5[]
We will learn the chapter 4 vocabulary and 1st and 2nd Declension endings, especially the 2nd neuter.

//end::Weekly-Overview-5[]

//tag::Assignment-011[]
===== Monday, August 19, 2024
Submit the Pandora story.
https://drive.google.com/file/d/1OmV19I2sgJsoaPeLTGu82G-Pj0mQygo_/view?usp=sharing[Chapter 3 Story]

Start studying
https://drive.google.com/file/d/1OoVag_dA8ARAIj2Pl727KlzV_t8HzYh7/view?usp=sharing[Chapter 4 Vocabulary]

//end::Assignment-011[]
//tag::Assignment-012[]
===== Tuesday, August 20, 2024
We will learn about second declension neuter nouns and adjectives as well as substantives and forms of sum.

We will translate most of the homework for chapter 4.

https://drive.google.com/file/d/1OlC2evJRMQE3V3aQaWAyYig86PDubXgc/view?usp=sharing[Chapter 4 Homework]


//end::Assignment-012[]
//tag::Assignment-013[]
===== Wednesday, August 21, 2024
Finish 
https://drive.google.com/file/d/1OlC2evJRMQE3V3aQaWAyYig86PDubXgc/view?usp=sharing[Chapter 4 Homework]
and 
https://drive.google.com/file/d/1OnHL1RdhkyD_JU0OYUGEFSjoUp-nMIuJ/view?usp=sharing[Chapter 4 Story]

Study 
https://drive.google.com/file/d/1OoVag_dA8ARAIj2Pl727KlzV_t8HzYh7/view?usp=sharing[Chapter 4 Vocabulary]
and the 1st and 2nd Declension endings, especially the 2nd neuter.

//end::Assignment-013[]
//tag::Assignment-014[]
===== Thursday, August 22, 2024
Submit 
https://drive.google.com/file/d/1OlC2evJRMQE3V3aQaWAyYig86PDubXgc/view?usp=sharing[Chapter 4 Homework]
and 
https://drive.google.com/file/d/1OnHL1RdhkyD_JU0OYUGEFSjoUp-nMIuJ/view?usp=sharing[Chapter 4 Story]

Study 
https://drive.google.com/file/d/1OoVag_dA8ARAIj2Pl727KlzV_t8HzYh7/view?usp=sharing[Chapter 4 Vocabulary]
and the 1st and 2nd Declension endings, especially the 2nd neuter.

//end::Assignment-014[]
//tag::Assignment-015[]
===== Friday, August 23, 2024

//end::Assignment-015[]
//tag::Quiz-03[]
We will have a quiz over the chapter 4 vocabulary and the 1st and 2nd Declension endings, and especially the 2nd neuter.
//end::Quiz-03[]

//end::Week-5[]




==== Week 6
//tag::Week-6[]


//tag::Weekly-Overview-6[]
We will learn the future and imperfect tenses of the 1st and 2nd conjugation. We will also look at adjectives ending in -er.

//end::Weekly-Overview-6[]
//tag::Assignment-016[]
===== Monday, August 26, 2024
Study
https://drive.google.com/file/d/1OoQ1xVSs64KbuJEk4KV6yzQXEzWmm2jr/view?usp=sharing[Chapter 5 Vocabulary].

Complete and Submit
https://drive.google.com/file/d/1OqCdbdTJ4ujUSYBAlyVPb-XaE5s5IuHm/view?usp=sharing[Chapter 5 Homework].

//end::Assignment-016[]
//tag::Assignment-017[]
===== Tuesday, August 27, 2024

// Make suplimental reading.

//end::Assignment-017[]
//tag::Assignment-018[]
===== Wednesday, August 28, 2024
Study
https://drive.google.com/file/d/1OoQ1xVSs64KbuJEk4KV6yzQXEzWmm2jr/view?usp=sharing[Chapter 5 Vocabulary].

Translate
https://drive.google.com/file/d/1OqN_3-ngofLc2C2GR0Bvfbpc5dAfGrkS/view?usp=sharing[Chapter 5 Story].


//end::Assignment-018[]
//tag::Assignment-019[]
===== Thursday, August 29, 2024
Study
https://drive.google.com/file/d/1OoQ1xVSs64KbuJEk4KV6yzQXEzWmm2jr/view?usp=sharing[Chapter 5 Vocabulary].

Submit 
//  suplimental reading.
and
https://drive.google.com/file/d/1OqN_3-ngofLc2C2GR0Bvfbpc5dAfGrkS/view?usp=sharing[Chapter 5 Story]

//end::Assignment-019[]
//tag::Assignment-020[]
===== Friday, August 30, 2024

//end::Assignment-020[]
//tag::Quiz-04[]
We will have a quiz over 
https://drive.google.com/file/d/1OoQ1xVSs64KbuJEk4KV6yzQXEzWmm2jr/view?usp=sharing[Chapter 5 Vocabulary],
the present, imperfect, and future tenses, and adjectives. 


//end::Quiz-04[]
//end::Week-6[]

==== Week 7
//tag::Week-7[]
Chapters 1-17

//tag::Weekly-Overview-7[]
7

//end::Weekly-Overview-7[]
//tag::Assignment-021[]
===== Monday, September 2, 2024
*Labor Day*

//end::Assignment-021[]
//tag::Assignment-022[]
===== Tuesday, September 3, 2024
*Satellite Day*

Review work from 1-5.

Vocabulary:

https://drive.google.com/file/d/1A70nrAUy-A_WOe77dW66EiYtrfc0_oGE/view?usp=share_link[Chapter 1 and 2 Vocabulary], 
https://drive.google.com/file/d/1OphxduV7WujulzLsxwIeXoXO_XWuT71U/view?usp=share_link[Chapter 3 Vocabulary], 
https://drive.google.com/file/d/1OoVag_dA8ARAIj2Pl727KlzV_t8HzYh7/view?usp=sharing[Chapter 4 Vocabulary], 
https://drive.google.com/file/d/1OoQ1xVSs64KbuJEk4KV6yzQXEzWmm2jr/view?usp=sharing[Chapter 5 Vocabulary] 

// more suplimental reading.


//end::Assignment-022[]
//tag::Assignment-023[]
===== Wednesday, September 4, 2024
Review work from 1-5.

Vocabulary:
 
https://drive.google.com/file/d/1A70nrAUy-A_WOe77dW66EiYtrfc0_oGE/view?usp=share_link[Chapter 1 and 2 Vocabulary], 
https://drive.google.com/file/d/1OphxduV7WujulzLsxwIeXoXO_XWuT71U/view?usp=share_link[Chapter 3 Vocabulary], 
https://drive.google.com/file/d/1OoVag_dA8ARAIj2Pl727KlzV_t8HzYh7/view?usp=sharing[Chapter 4 Vocabulary], 
https://drive.google.com/file/d/1OoQ1xVSs64KbuJEk4KV6yzQXEzWmm2jr/view?usp=sharing[Chapter 5 Vocabulary] 

// more suplimental reading.

//end::Assignment-023[]
//tag::Assignment-024[]
===== Thursday, September 5, 2024
Review work from 1-5.

Vocabulary:
 
https://drive.google.com/file/d/1A70nrAUy-A_WOe77dW66EiYtrfc0_oGE/view?usp=share_link[Chapter 1 and 2 Vocabulary], 
https://drive.google.com/file/d/1OphxduV7WujulzLsxwIeXoXO_XWuT71U/view?usp=share_link[Chapter 3 Vocabulary], 
https://drive.google.com/file/d/1OoVag_dA8ARAIj2Pl727KlzV_t8HzYh7/view?usp=sharing[Chapter 4 Vocabulary], 
https://drive.google.com/file/d/1OoQ1xVSs64KbuJEk4KV6yzQXEzWmm2jr/view?usp=sharing[Chapter 5 Vocabulary] 

// more suplimental reading.

//end::Assignment-024[]
//tag::Assignment-025[]
===== Friday, September 6, 2024

//end::Assignment-025[]

//end::Week-7[]

=== Module 2 -- Review 2
==== Week 8
//tag::Week-8[]


//tag::Weekly-Overview-8[]


//end::Weekly-Overview-8[]
//tag::Assignment-026[]
===== Monday, September 9, 2024

Study
https://drive.google.com/file/d/1OpQ7U8nzoFj0VkocVH4KJzS8OG5q8Ecp/view?usp=share_link[Chapter 6 Vocabulary] https://drive.google.com/file/d/1OnZ3FdygTdtwr9v4yI-XXMEGt19CFM9V/view?usp=share_link[Chapter 6 Homework]

Study {ch7voc}.


//end::Assignment-026[]
//tag::Assignment-027[]
===== Tuesday, September 10, 2024

//end::Assignment-027[]
//tag::Assignment-028[]
===== Wednesday, September 11, 2024
https://drive.google.com/file/d/1Oo2lhsKlCIDtUc0fZnYRaTE6rCy22YfU/view?usp=share_link[Chapter 6 Story]

//end::Assignment-028[]
//tag::Assignment-029[]
===== Thursday, September 12, 2024

https://drive.google.com/file/d/1Oo2lhsKlCIDtUc0fZnYRaTE6rCy22YfU/view?usp=share_link[Chapter 6 Story]

//end::Assignment-029[]
//tag::Assignment-030[]
===== Friday, September 13, 2024

//end::Assignment-030[]
//tag::Quiz-05[]
Quiz over chapter 6 vocabulary and grammar.

//end::Quiz-05[]
//end::Week-8[]


==== Week 9
//tag::Week-9[]
Chapter 7

https://drive.google.com/file/d/1OoEJScryLmCn5J-Gzz8kuOwwz7QWG4t8/view?usp=share_link[Chapter 7 Story]

//tag::Weekly-Overview-9[]
We will learn about 3rd declension nouns.

//end::Weekly-Overview-9[]
//tag::Assignment-031[]
===== Monday, September 16, 2024

Study
https://drive.google.com/file/d/1OpHGZ-rP5bunDBuG6Z92R09_3ZNoa2gN/view?usp=share_link[Chapter 7 Vocabulary].


Complete and submit
https://drive.google.com/file/d/1Oo6Cp7M6Bkg48OSFmIkGR101_iCIZAgA/view?usp=share_link[Chapter 7 Homework]

//end::Assignment-031[]
//tag::Assignment-032[]
===== Tuesday, September 17, 2024
*Chapel Day*

//end::Assignment-032[]
//tag::Assignment-033[]
===== Wednesday, September 18, 2024
Study
https://drive.google.com/file/d/1OpHGZ-rP5bunDBuG6Z92R09_3ZNoa2gN/view?usp=share_link[Chapter 7 Vocabulary].

//end::Assignment-033[]
//tag::Assignment-034[]
===== Thursday, September 19, 2024
Study
https://drive.google.com/file/d/1OpHGZ-rP5bunDBuG6Z92R09_3ZNoa2gN/view?usp=share_link[Chapter 7 Vocabulary].

Complete and upload https://drive.google.com/file/d/1OoEJScryLmCn5J-Gzz8kuOwwz7QWG4t8/view?usp=sharing[Chapter 7 Story]

//end::Assignment-034[]
//tag::Assignment-035[]
===== Friday, September 20, 2024

//end::Assignment-035[]
//tag::Quiz-06[]
Quiz over chapter 7 vocabulary and grammar.

//end::Quiz-06[]
//end::Week-9[]

==== Week 10
//tag::Week-10[]
Chapters 18-27

//tag::Weekly-Overview-10[]
10

//end::Weekly-Overview-10[]
//end::Week-10[]

==== Week 11
//tag::Week-11[]
//tag::Weekly-Overview-11[]
11

//end::Weekly-Overview-11[]
//tag::Assignment-036[]
===== Monday, September 30, 2024

//end::Assignment-036[]
//tag::Assignment-037[]
===== Tuesday, October 1, 2024
We translated the 

https://drive.google.com/file/d/1k90cSbXq7RZ6XWMcUAz9g0LnQ1e-kUTq/view?usp=share_link[story of Hannibal].

//end::Assignment-037[]
//tag::Assignment-038[]
===== Wednesday, October 2, 2024
Study for your test.

//end::Assignment-038[]
//tag::Assignment-039[]
===== Thursday, October 3, 2024
Submit the 
https://drive.google.com/file/d/1k90cSbXq7RZ6XWMcUAz9g0LnQ1e-kUTq/view?usp=share_link[translation].

Study for your test.
//end::Assignment-039[]
//tag::Assignment-040[]
===== Friday, October 4, 2024

//end::Assignment-040[]

//tag::Test-01[]
Test over chapters 1-7. It will cover the vocabulary and grammar from these chapters. 

//end::Test-01[]
//tag::Test-02[]
Test 2

//end::Test-02[]

//end::Week-11[]


== 2nd Quarter
=== Module 3 -- Chapters 28-30

==== Week 12
//tag::Week-12[]
//tag::Weekly-Overview-12[]
We will cover 3rd conjugation presents, imperfects and futures.

//end::Weekly-Overview-12[]

//tag::Assignment-041[]
===== Monday, October 7, 2024
Complete the first page of 
https://drive.google.com/file/d/119flPHgLasY9PTOzc6sZMAibWNtyGU0s/view?usp=share_link[Chapter 8 Homework]

Study 
https://drive.google.com/file/d/11ENrejuFFu7XsM_gKZgWibrnEQV3sKdh/view?usp=share_link[Chapter 8 Vocabulary]

//end::Assignment-041[]
//tag::Assignment-042[]
===== Tuesday, October 8, 2024

//end::Assignment-042[]
//tag::Assignment-043[]
===== Wednesday, October 9, 2024
Finish 
https://drive.google.com/file/d/119flPHgLasY9PTOzc6sZMAibWNtyGU0s/view?usp=share_link[Chapter 8 Homework]

Study 
https://drive.google.com/file/d/11ENrejuFFu7XsM_gKZgWibrnEQV3sKdh/view?usp=share_link[Chapter 8 Vocabulary]

//end::Assignment-043[]
//tag::Assignment-044[]
===== Thursday, October 10, 2024
Submit
https://drive.google.com/file/d/119flPHgLasY9PTOzc6sZMAibWNtyGU0s/view?usp=share_link[Chapter 8 Homework]

Study 
https://drive.google.com/file/d/11ENrejuFFu7XsM_gKZgWibrnEQV3sKdh/view?usp=share_link[Chapter 8 Vocabulary]

//end::Assignment-044[]
//tag::Assignment-045[]
===== Friday, October 11, 2024

//end::Assignment-045[]
//tag::Quiz-07[]
We will have a quiz over chapter 8 vocabulary and 3rd conjugation presents, imperfects and futures.

//end::Quiz-07[]
//end::Week-12[]

==== Week 13
//tag::Week-13[]
//tag::Weekly-Overview-13[]
We will cover several special adjectives.

//end::Weekly-Overview-13[]
//tag::Assignment-046[]
===== Monday, October 14, 2024
Complete and upload the first page front and back of 
https://drive.google.com/file/d/1100pUowpAR2vZN9_FLy_i0WX7T_O2VnN/view?usp=share_link[Chapter 9 Homework]

Study
https://drive.google.com/file/d/110X6BEhL1S0lVR_Le0anY1xygsC8E7hF/view?usp=share_link[Chapter 9 Vocabulary]

//end::Assignment-046[]
//tag::Assignment-047[]
===== Tuesday, October 15, 2024

//end::Assignment-047[]
//tag::Assignment-048[]
===== Wednesday, October 16, 2024
Complete the rest of
https://drive.google.com/file/d/1100pUowpAR2vZN9_FLy_i0WX7T_O2VnN/view?usp=share_link[Chapter 9 Homework]

Study
https://drive.google.com/file/d/110X6BEhL1S0lVR_Le0anY1xygsC8E7hF/view?usp=share_link[Chapter 9 Vocabulary]

//end::Assignment-048[]
//tag::Assignment-049[]
===== Thursday, October 17, 2024
Submit the rest of 
https://drive.google.com/file/d/1100pUowpAR2vZN9_FLy_i0WX7T_O2VnN/view?usp=share_link[Chapter 9 Homework]

Study
https://drive.google.com/file/d/110X6BEhL1S0lVR_Le0anY1xygsC8E7hF/view?usp=share_link[Chapter 9 Vocabulary]

//end::Assignment-049[]
//tag::Assignment-050[]
===== Friday, October 18, 2024

//end::Assignment-050[]
//tag::Quiz-08[]
We will have a quiz over chapter 9 vocabulary and special adjectives.

//end::Quiz-08[]
//end::Week-13[]

==== Week 14
//tag::Week-14[]
//tag::Weekly-Overview-14[]
14

//end::Weekly-Overview-14[]
//tag::Assignment-051[]
===== Monday, October 21, 2024
Complete and upload the first page of
https://drive.google.com/file/d/13b7z2CTxwmpI-TVwEmR_VK660CsDVymu/view?usp=sharing[Chapter 10 Homework]

Study https://drive.google.com/file/d/13aK7kofFKOICRE1hfN0YV6FD7vwG6h45/view?usp=sharing[Chapter 10 Vocabulary]

//end::Assignment-051[]
//tag::Assignment-052[]
===== Tuesday, October 22, 2024
*Seminar Day*

//end::Assignment-052[]
//tag::Assignment-053[]
===== Wednesday, October 23, 2024
Complete the rest of 
https://drive.google.com/file/d/13b7z2CTxwmpI-TVwEmR_VK660CsDVymu/view?usp=sharing[Chapter 10 Homework]

Study https://drive.google.com/file/d/13aK7kofFKOICRE1hfN0YV6FD7vwG6h45/view?usp=sharing[Chapter 10 Vocabulary]

//end::Assignment-053[]
//tag::Assignment-054[]
===== Thursday, October 24, 2024
Up the rest of
https://drive.google.com/file/d/13b7z2CTxwmpI-TVwEmR_VK660CsDVymu/view?usp=sharing[Chapter 10 Homework]

Study https://drive.google.com/file/d/13aK7kofFKOICRE1hfN0YV6FD7vwG6h45/view?usp=sharing[Chapter 10 Vocabulary]

//end::Assignment-054[]
//tag::Assignment-055[]
===== Friday, October 25, 2024

//end::Assignment-055[]
//tag::Quiz-09[]
We will have a quiz focusing on vocabulary from chapter 10 and verb forms.

//end::Quiz-09[]
//end::Week-14[]


==== Week 15
//tag::Week-15[]
//tag::Weekly-Overview-15[]
15

//end::Weekly-Overview-15[]

//tag::Assignment-056[]
===== Monday, October 28, 2024

Complete and upload the first page of the homework.

https://drive.google.com/open?id=1GDaYI-DNincwC5RmocT2SlPHg8j9f0n9&usp=drive_fs[Chapter 11 Vocabulary]

//end::Assignment-056[]
//tag::Assignment-057[]
===== Tuesday, October 29, 2024

//end::Assignment-057[]
//tag::Assignment-058[]
===== Wednesday, October 30, 2024
Finish the packet from class.

https://drive.google.com/open?id=1GDaYI-DNincwC5RmocT2SlPHg8j9f0n9&usp=drive_fs[Chapter 11 Vocabulary]

//end::Assignment-058[]
//tag::Assignment-059[]
===== Thursday, October 31, 2024
Submit the rest of the packet.

https://drive.google.com/open?id=1GDaYI-DNincwC5RmocT2SlPHg8j9f0n9&usp=drive_fs[Chapter 11 Vocabulary]

//end::Assignment-059[]
//tag::Assignment-060[]
===== Friday, November 1, 2024

//end::Assignment-060[]
//tag::Quiz-10[]
Quiz 10

//end::Quiz-10[]
//end::Week-15[]

==== Week 16
//tag::Week-16[]
//tag::Weekly-Overview-16[]
16

//end::Weekly-Overview-16[]

//tag::Assignment-061[]
===== Monday, November 4, 2024
Work on 
https://drive.google.com/open?id=16qAgNNpiLyy2Irks9txlQmrtndRSDE4H&usp=drive_fs[Review Reading]

//end::Assignment-061[]
//tag::Assignment-062[]
===== Tuesday, November 5, 2024
*Satellite Day*

Work on 
https://drive.google.com/open?id=16qAgNNpiLyy2Irks9txlQmrtndRSDE4H&usp=drive_fs[Review Reading]

//end::Assignment-062[]
//tag::Assignment-063[]
===== Wednesday, November 6, 2024

Work on 
https://drive.google.com/open?id=16qAgNNpiLyy2Irks9txlQmrtndRSDE4H&usp=drive_fs[Review Reading]

//end::Assignment-063[]
//tag::Assignment-064[]
===== Thursday, November 7, 2024

Submit
https://drive.google.com/open?id=16qAgNNpiLyy2Irks9txlQmrtndRSDE4H&usp=drive_fs[Review Reading]

//end::Assignment-064[]
//tag::Assignment-065[]
===== Friday, November 8, 2024

//end::Assignment-065[]
//tag::Test-03[]


//end::Test-03[]
//end::Week-16[]


=== Module 4 -- Chapters 31-32

==== Week 17
//tag::Week-17[]
//tag::Weekly-Overview-17[]
17

//end::Weekly-Overview-17[]

//tag::Assignment-066[]
===== Monday, November 11, 2024

Complete and upload the front of the first page of 
https://drive.google.com/file/d/17puGUWJ_OJubtghIg3Do0Dcqngosopib/view?usp=sharing[Chapter 12 Homework].

Study 
https://drive.google.com/file/d/17hvXDjPEje48ueay-I30Dfh6OAv-9dNk/view?usp=sharing[Chapter 12 Vocabulary]


//end::Assignment-066[]
//tag::Assignment-067[]
===== Tuesday, November 12, 2024

//end::Assignment-067[]
//tag::Assignment-068[]
===== Wednesday, November 13, 2024

Complete the rest of
https://drive.google.com/file/d/17puGUWJ_OJubtghIg3Do0Dcqngosopib/view?usp=sharing[Chapter 12 Homework].

Study 
https://drive.google.com/file/d/17hvXDjPEje48ueay-I30Dfh6OAv-9dNk/view?usp=sharing[Chapter 12 Vocabulary]

//end::Assignment-068[]
//tag::Assignment-069[]
===== Thursday, November 14, 2024

Upload the rest of
https://drive.google.com/file/d/17puGUWJ_OJubtghIg3Do0Dcqngosopib/view?usp=sharing[Chapter 12 Homework].

Study 
https://drive.google.com/file/d/17hvXDjPEje48ueay-I30Dfh6OAv-9dNk/view?usp=sharing[Chapter 12 Vocabulary]

//end::Assignment-069[]
//tag::Assignment-070[]
===== Friday, November 15, 2024

//end::Assignment-070[]
//tag::Quiz-11[]
Quiz 11

//end::Quiz-11[]
//end::Week-17[]

==== Week 18
//tag::Week-18[]
//tag::Weekly-Overview-18[]
18

//end::Weekly-Overview-18[]

//tag::Assignment-071[]
===== Monday, November 18, 2024

Complete and upload the first page of the chapter 13 homework.

Study https://drive.google.com/file/d/17oQgYtgzCpnczlnrQYKk8ji7gC1VuBfZ/view?usp=sharing[Chapter 13 Vocabulary]

//end::Assignment-071[]
//tag::Assignment-072[]
===== Tuesday, November 19, 2024
*Chapel Day*

//end::Assignment-072[]
//tag::Assignment-073[]
===== Wednesday, November 20, 2024
Complete the rest of chapter 13 homework.

Study https://drive.google.com/file/d/17oQgYtgzCpnczlnrQYKk8ji7gC1VuBfZ/view?usp=sharing[Chapter 13 Vocabulary]

//end::Assignment-073[]
//tag::Assignment-074[]
===== Thursday, November 21, 2024

Upload the rest of chapter 13 homework.

Study https://drive.google.com/file/d/17oQgYtgzCpnczlnrQYKk8ji7gC1VuBfZ/view?usp=sharing[Chapter 13 Vocabulary]

//end::Assignment-074[]
//tag::Assignment-075[]
===== Friday, November 22, 2024

//end::Assignment-075[]
//tag::Quiz-12[]
Quiz 12

//end::Quiz-12[]
//end::Week-18[]

==== Week 19
//tag::Week-19[]
//tag::Weekly-Overview-19[]
19

//end::Weekly-Overview-19[]
//end::Week-19[]

==== Week 20
//tag::Week-20[]
//tag::Weekly-Overview-20[]
20

//end::Weekly-Overview-20[]

//tag::Assignment-076[]
===== Monday, December 2, 2024

Review material from chapters 8-13.

//end::Assignment-076[]
//tag::Assignment-077[]
===== Tuesday, December 3, 2024
*Seminar Day*

We did started a review section in class. 


//end::Assignment-077[]
//tag::Assignment-078[]
===== Wednesday, December 4, 2024

The first two pages are the same as what I handed out in class. Finish the last three pages.
https://drive.google.com/file/d/1ABBbF4JHWE1Yw5xc8IRJjHP_v7VLXkdQ/view?usp=sharing[Review 8-10]

//end::Assignment-078[]
//tag::Assignment-079[]
===== Thursday, December 5, 2024

Upload the review for 8-10.

//end::Assignment-079[]
//tag::Assignment-080[]
===== Friday, December 6, 2024

//work on review for 11-13.

//end::Assignment-080[]
//tag::Quiz-13[]
//Quiz 13

//end::Quiz-13[]
//end::Week-20[]

==== Week 21
//tag::Week-21[]
//tag::Weekly-Overview-21[]
21

//end::Weekly-Overview-21[]

//tag::Assignment-081[]
===== Monday, December 9, 2024

//end::Assignment-081[]
//tag::Assignment-082[]
===== Tuesday, December 10, 2024

//end::Assignment-082[]
//tag::Assignment-083[]
===== Wednesday, December 11, 2024

//end::Assignment-083[]
//tag::Assignment-084[]
===== Thursday, December 12, 2024

//end::Assignment-084[]
//tag::Assignment-085[]
===== Friday, December 13, 2024
*Last Day of School*

//end::Assignment-085[]
//tag::Test-04[]
Test 4

//end::Test-04[]
//end::Week-21[]







== 3rd Quarter
=== Module 5 -- Chapters 33-34
==== Week 22
//tag::Week-22[]
22

//tag::Weekly-Overview-22[]


//end::Weekly-Overview-22[]
//tag::Assignment-086[]
===== Monday, December 30, 2024
*Holiday*

//end::Assignment-086[]
//tag::Assignment-087[]
===== Tuesday, December 31, 2024
*Holiday*

//end::Assignment-087[]
//tag::Assignment-088[]
===== Wednesday, January 1, 2024
*Holiday*
 
//end::Assignment-088[]
//tag::Assignment-089[]
===== Thursday, January 2, 2024
*Satellite Day*

Review chapters 1-14 from the first semester.

//end::Assignment-089[]
//tag::Assignment-090[]
===== Friday, January 3, 2024
*Satellite Day*

Review chapters 1-14 from the first semester.


//end::Assignment-090[]
//end::Week-22[]
Review Chapters 13-17


==== Week 23
//tag::Week-23[]
//tag::Weekly-Overview-23[]

We will learn numerals, genitive of the whole, and ablatives of time.

//end::Weekly-Overview-23[]
*Teacher Work Day*

//tag::Assignment-091[]
===== Monday, January 6, 2025
*Satellite Day*

Review chapters 1-14 from the first semester.


//end::Assignment-091[]
*First Day Back in Class*

//tag::Assignment-092[]
===== Tuesday, January 7, 2025
We worked on
https://drive.google.com/file/d/1E0Uh72clrn7hAz4dQUyPvv5JYXzvX-fd/view?usp=sharing[Chapter 15 Homework]


//end::Assignment-092[]
//tag::Assignment-093[]
===== Wednesday, January 8, 2025

Study
https://drive.google.com/file/d/1E0Uh72clrn7hAz4dQUyPvv5JYXzvX-fd/view?usp=sharing[Chapter 15 Vocabulary]

Review
https://drive.google.com/open?id=1E0ZJmR_koiDVL0y65bg8trFImLLgCWx9&usp=drive_fs[Numerals]

Work on 
https://drive.google.com/file/d/1E0Uh72clrn7hAz4dQUyPvv5JYXzvX-fd/view?usp=sharing[Chapter 15 Homework]

//end::Assignment-093[]
//tag::Assignment-094[]
===== Thursday, January 9, 2025

Study
https://drive.google.com/file/d/1E0Uh72clrn7hAz4dQUyPvv5JYXzvX-fd/view?usp=sharing[Chapter 15 Vocabulary]

Review
https://drive.google.com/open?id=1E0ZJmR_koiDVL0y65bg8trFImLLgCWx9&usp=drive_fs[Numerals]

Finish and submit
https://drive.google.com/file/d/1E0Uh72clrn7hAz4dQUyPvv5JYXzvX-fd/view?usp=sharing[Chapter 15 Homework]

//end::Assignment-094[]
//tag::Assignment-095[]
===== Friday, January 10, 2025

//end::Assignment-095[]
//tag::Quiz-14[]

Know the chapter 15 vocabulary, be familiar with the numerals, and review noun forms.


//end::Quiz-14[]
//end::Week-23[]

==== Week 24
//tag::Week-24[]
//tag::Weekly-Overview-24[]
24

//end::Weekly-Overview-24[]

//tag::Assignment-096[]
===== Monday, January 13, 2025

Study
https://drive.google.com/file/d/1E0Uh72clrn7hAz4dQUyPvv5JYXzvX-fd/view?usp=sharing[Chapter 15 Vocabulary]

Review
https://drive.google.com/open?id=1E0ZJmR_koiDVL0y65bg8trFImLLgCWx9&usp=drive_fs[Numerals]

//end::Assignment-096[]
//tag::Assignment-097[]
===== Tuesday, January 14, 2025

We introduced 3rd declension adjectives, and we reviewed attributive adjectives, predicate adjectives, substantive adjectives, and objective complements.

//end::Assignment-097[]
//tag::Assignment-098[]
===== Wednesday, January 15, 2025

Complete https://drive.google.com/file/d/1EP2z8f4WqUr3Y3-AojP6eJCRDTMH-fHr/view?usp=sharing[Chapter 16 Homework]

Study https://drive.google.com/file/d/1EOs5DlJf4lPs0ImLMVhcb3iuso6qLnnU/view?usp=sharing[Chapter 16 Vocabulary]

//end::Assignment-098[]
//tag::Assignment-099[]
===== Thursday, January 16, 2025

Submit https://drive.google.com/file/d/1EP2z8f4WqUr3Y3-AojP6eJCRDTMH-fHr/view?usp=sharing[Chapter 16 Homework]

Study https://drive.google.com/file/d/1EOs5DlJf4lPs0ImLMVhcb3iuso6qLnnU/view?usp=sharing[Chapter 16 Vocabulary]

//end::Assignment-099[]
//tag::Assignment-100[]
===== Friday, January 17, 2025
We learned the relative pronoun and worked on 
https://drive.google.com/open?id=1ESCruxuKR3mFF4CL2tKs200pW3A-Auy9&usp=drive_fs[Chapter 17 Homework]

//end::Assignment-100[]
//tag::Quiz-15[]
Study 
https://drive.google.com/file/d/1EOs5DlJf4lPs0ImLMVhcb3iuso6qLnnU/view?usp=sharing[Chapter 16 Vocabulary]
, 
https://drive.google.com/file/d/1EP2z8f4WqUr3Y3-AojP6eJCRDTMH-fHr/view?usp=sharing[homework transations]
, 3rd declension adjectives, attributive adjectives, predicate adjectives, substantive adjectives, and objective complements.

//end::Quiz-15[]
//end::Week-24[]


==== Week 25
//tag::Week-25[]
Review Chapters 18-21
//tag::Weekly-Overview-25[]
25

//end::Weekly-Overview-25[]
//tag::Assignment-101[]
===== Monday, January 20, 2025
*Holiday-MLK Day*

//end::Assignment-101[]
//tag::Assignment-102[]
===== Tuesday, January 21, 2025

We finished 
https://drive.google.com/open?id=1ESCruxuKR3mFF4CL2tKs200pW3A-Auy9&usp=drive_fs[Chapter 17 Homework]

We started https://drive.google.com/open?id=1ESr3YdRCeB3qdMPvDGcOmiMZ_0RTnd__&usp=drive_fs[Review 16 and 17]

//end::Assignment-102[]
//tag::Assignment-103[]
===== Wednesday, January 22, 2025

Study https://drive.google.com/file/d/19eiCtryJkcA9NMyet-bSACh86CqXzojY/view?usp=sharing[Chapter 17 Vocabulary]

//end::Assignment-103[]
//tag::Assignment-104[]
===== Thursday, January 23, 2025

Study https://drive.google.com/file/d/19eiCtryJkcA9NMyet-bSACh86CqXzojY/view?usp=sharing[Chapter 17 Vocabulary]

Submit https://drive.google.com/open?id=1ESCruxuKR3mFF4CL2tKs200pW3A-Auy9&usp=drive_fs[Chapter 17 Homework]

//end::Assignment-104[]
//tag::Assignment-105[]
===== Friday, January 24, 2025

//end::Assignment-105[]
//tag::Quiz-16[]
Quiz 16

//end::Quiz-16[]
//end::Week-25[]

==== Week 26
//tag::Week-26[]
Review Chapters 22-24
//tag::Weekly-Overview-26[]
26

//end::Weekly-Overview-26[]
//tag::Assignment-106[]
===== Monday, January 27, 2025

Complete and submit https://drive.google.com/open?id=1EnuXaWZObiAcnlbK3IA32wUiwz9RvvVj&usp=drive_fs[Chapter 18 Homework]

Study https://drive.google.com/open?id=1EnBOeC39ShzxbjKFCrFr5Co9r2CtCvAm&usp=drive_fs[Chapter 18 Vocabulary]

//end::Assignment-106[]
//tag::Assignment-107[]
===== Tuesday, January 28, 2025

//end::Assignment-107[]
//tag::Assignment-108[]
===== Wednesday, January 29, 2025

Complete the review handout from class.

//Complete https://drive.google.com/file/d/1EvTkW9gOQLEFxw0oakqp_ASirCHdCTsK/view?usp=sharing[Chatper 18 Story]

Study https://drive.google.com/open?id=1EnBOeC39ShzxbjKFCrFr5Co9r2CtCvAm&usp=drive_fs[Chapter 18 Vocabulary]

//end::Assignment-108[]
//tag::Assignment-109[]
===== Thursday, January 30, 2025

//Submit https://drive.google.com/file/d/1EvTkW9gOQLEFxw0oakqp_ASirCHdCTsK/view?usp=sharing[Chatper 18 Story]

Submit the review packet from class.

Study https://drive.google.com/open?id=1EnBOeC39ShzxbjKFCrFr5Co9r2CtCvAm&usp=drive_fs[Chapter 18 Vocabulary]

//end::Assignment-109[]
//tag::Assignment-110[]
===== Friday, January 31, 2025

//end::Assignment-110[]

//tag::Quiz-17[]

Quiz over chapter 18

//end::Quiz-17[]

//tag::Test-05[]
No test

//end::Test-05[]
//end::Week-26[]

=== Module 6 -- Chapters 35-36
==== Week 27
//tag::Week-27[]
Review Chapters 25-27
//tag::Weekly-Overview-27[]
27

//end::Weekly-Overview-27[]
//tag::Assignment-111[]
===== Monday, February 3, 2025

Complete and submit https://drive.google.com/open?id=1EoaXAzkBPQUW3sLw1Q0wdy6Ct58wHHqA&usp=drive_fs[Chapter 19 Homework]

Study https://drive.google.com/open?id=1Enbuvu007lQCNjnIKodeRxGl42kyyNXD&usp=drive_fs[Chapter 19 Vocabulary]

//end::Assignment-111[]
//tag::Assignment-112[]
===== Tuesday, February 4, 2025

//end::Assignment-112[]
//tag::Assignment-113[]
===== Wednesday, February 5, 2025

Study https://drive.google.com/open?id=1Enbuvu007lQCNjnIKodeRxGl42kyyNXD&usp=drive_fs[Chapter 19 Vocabulary]

Complete https://drive.google.com/open?id=1EvZxhqcth6ybCyzZRYnGUZpnkH7mIYGb&usp=drive_fs[Chapter 19 Story]

//end::Assignment-113[]
//tag::Assignment-114[]
===== Thursday, February 6, 2025

Study https://drive.google.com/open?id=1Enbuvu007lQCNjnIKodeRxGl42kyyNXD&usp=drive_fs[Chapter 19 Vocabulary]

Submit https://drive.google.com/open?id=1EvZxhqcth6ybCyzZRYnGUZpnkH7mIYGb&usp=drive_fs[Chapter 19 Story]

//end::Assignment-114[]
//tag::Assignment-115[]
===== Friday, February 7, 2025


//end::Assignment-115[]

//end::Week-27[]


==== Week 28
//tag::Week-28[]
//tag::Weekly-Overview-28[]
28

//end::Weekly-Overview-28[]
//tag::Assignment-116[]
===== Monday, February 10, 2025

Complete and submit https://drive.google.com/open?id=1EpViIdAiuK1eiu0mRXBm9xqIKddH3NYC&usp=drive_fs[Chapter 20 Homework]


Study https://drive.google.com/open?id=1Ep3i6xtlLxm2mDZ2fgPJvxWnVfFG-tar&usp=drive_fs[Chapter 20 Vocabulary]

//end::Assignment-116[]
//tag::Assignment-117[]
===== Tuesday, February 11, 2025



//end::Assignment-117[]
//tag::Assignment-118[]
===== Wednesday, February 12, 2025

Study https://drive.google.com/open?id=1Ep3i6xtlLxm2mDZ2fgPJvxWnVfFG-tar&usp=drive_fs[Chapter 20 Vocabulary]

Complete https://drive.google.com/file/d/1RH0ZC9FpQVGHEEx4c0l76J6axYUhUjJa/view?usp=sharing[Chapter 20 Story]

//end::Assignment-118[]
//tag::Assignment-119[]
===== Thursday, February 13, 2025

Study https://drive.google.com/open?id=1Ep3i6xtlLxm2mDZ2fgPJvxWnVfFG-tar&usp=drive_fs[Chapter 20 Vocabulary]

Submit https://drive.google.com/file/d/1RH0ZC9FpQVGHEEx4c0l76J6axYUhUjJa/view?usp=sharing[Chapter 20 Story]

//end::Assignment-119[]
//tag::Assignment-120[]
===== Friday, February 14, 2025

//end::Assignment-120[]
//tag::Quiz-18[]

Quiz over chapter 20.

//end::Quiz-18[]
//end::Week-28[]

==== Week 29
//tag::Week-29[]
//tag::Weekly-Overview-29[]
29

//end::Weekly-Overview-29[]
//tag::Assignment-121[]
===== Monday, February 17, 2025

Complete https://drive.google.com/file/d/1QyHD_V0_vO3BOXixpip19cg7s1i18AUq/view?usp=sharing[Chapter 21 Homework]

Study https://drive.google.com/file/d/1LiJn9XHvEb51UOPyfmkJJ7DOtZzIdKt0/view?usp=sharing[Chapter 21 Vocabulary]

//end::Assignment-121[]
//tag::Assignment-122[]
===== Tuesday, February 18, 2025


//end::Assignment-122[]
//tag::Assignment-123[]
===== Wednesday, February 19, 2025

Complete 
https://drive.google.com/file/d/1EtHgZ0GKKtjB4j7hmRD75IcYSAGyg_hS/view?usp=sharing[Chapter 21 Story]

//end::Assignment-123[]
//tag::Assignment-124[]
===== Thursday, February 20, 2025

Submit
https://drive.google.com/file/d/1EtHgZ0GKKtjB4j7hmRD75IcYSAGyg_hS/view?usp=sharing[Chapter 21 Story]


//end::Assignment-124[]
//tag::Assignment-125[]
===== Friday, February 21, 2025
*Winter Holiday*

//end::Assignment-125[]
//tag::Quiz-19[]
Quiz 19

//end::Quiz-19[]

//end::Week-29[]


==== Week 30
//tag::Week-30[]
//tag::Weekly-Overview-30[]
30

//end::Weekly-Overview-30[]

//tag::Assignment-126[]
===== Monday, February 24, 2025

Complete the first page of 
https://drive.google.com/open?id=1EtnPz5yM5AwGmGte6PpwBFzHiYbZbthZ&usp=drive_fs[Chapter 22 Homework.]

Study
https://drive.google.com/open?id=1EtIYjVZRxIyDsXmApTPIF3Fe4TIEiu51&usp=drive_fs[Chapter 22 Vocabulary]

//end::Assignment-126[]
//tag::Assignment-127[]
===== Tuesday, February 25, 2025
Chapel Schedule

//end::Assignment-127[]
//tag::Assignment-128[]
===== Wednesday, February 26, 2025

Complete
https://drive.google.com/open?id=1EtnPz5yM5AwGmGte6PpwBFzHiYbZbthZ&usp=drive_fs[Chapter 22 Homework.]


//end::Assignment-128[]
//tag::Assignment-129[]
===== Thursday, February 27, 2025

Submit 
https://drive.google.com/open?id=1EtnPz5yM5AwGmGte6PpwBFzHiYbZbthZ&usp=drive_fs[Chapter 22 Homework.]


//end::Assignment-129[]
//tag::Assignment-130[]
===== Friday, February 28, 2025

//end::Assignment-130[]
//tag::Quiz-20[]

Quiz over chapters 21 and 22.

//end::Quiz-20[]
//end::Week-30[]

==== Week 31
//tag::Week-31[]
//tag::Weekly-Overview-31[]
31

//end::Weekly-Overview-31[]
//tag::Assignment-131[]
===== Monday, March 3, 2025

Complete https://drive.google.com/file/d/1Eqfo6vutDEKhkXFnT9VrxRx4E3ZAEvTZ/view?usp=sharing[Chapter 22 Story]

//end::Assignment-131[]
//tag::Assignment-132[]
===== Tuesday, March 4, 2025

//end::Assignment-132[]
//tag::Assignment-133[]
===== Wednesday, March 5, 2025

Study chapters 15-22.

//end::Assignment-133[]
//tag::Assignment-134[]
===== Thursday, March 6, 2025

Submit the translation from class Tuesday. 

Study chapters 15-22.


//end::Assignment-134[]
//tag::Assignment-135[]
===== Friday, March 7, 2025

End of 3rd term


//end::Assignment-135[]
//tag::Test-06[]

Test over chapters 15-22.

//end::Test-06[]
//end::Week-31[]


== 4th Quarter
=== Module 7 -- Chapters 37-38
==== Week 32
//tag::Week-32[]
//tag::Weekly-Overview-32[]
32

//end::Weekly-Overview-32[]
//tag::Assignment-136[]
===== Monday, March 10, 2025

Review https://drive.google.com/file/d/1LpPY-oGbwCj2NxcV7lDTQ37OTigt-Rti/view?usp=sharing[Chapter 23 Vocabulary]

//end::Assignment-136[]
//tag::Assignment-137[]
===== Tuesday, March 11, 2025

//end::Assignment-137[]
//tag::Assignment-138[]
===== Wednesday, March 12, 2025

Complete https://drive.google.com/file/d/1R4ESK1JxE03Xcs3iYCPXn5DIfDnJs6tQ/view?usp=sharing[Chapter 23 Homework]

Review https://drive.google.com/file/d/1LpPY-oGbwCj2NxcV7lDTQ37OTigt-Rti/view?usp=sharing[Chapter 23 Vocabulary]

//end::Assignment-138[]
//tag::Assignment-139[]
===== Thursday, March 13, 2025

Submit https://drive.google.com/file/d/1R4ESK1JxE03Xcs3iYCPXn5DIfDnJs6tQ/view?usp=sharing[Chapter 23 Homework]

Review https://drive.google.com/file/d/1LpPY-oGbwCj2NxcV7lDTQ37OTigt-Rti/view?usp=sharing[Chapter 23 Vocabulary]

//end::Assignment-139[]
//tag::Assignment-140[]
===== Friday, March 14, 2025

//end::Assignment-140[]
//tag::Quiz-21[]

Quiz over chapter 23.

//end::Quiz-21[]
//end::Week-32[]


==== Week 33
//tag::Week-33[]
//tag::Weekly-Overview-33[]
33

//end::Weekly-Overview-33[]

//tag::Assignment-141[]
===== Monday, March 17, 2025

Submit the frist two pages of 
https://drive.google.com/file/d/1R5f-vstdJNHc34THTplN4hk9lFHjVjI6/view?usp=sharing[Lesson 24 Homework]

Study 
https://drive.google.com/file/d/1Lpo1wNDxa9Uy-7ax98dHQzeNFsbhFlXj/view?usp=sharing[Lesson 24 Vocabulary]

//end::Assignment-141[]
//tag::Assignment-142[]
===== Tuesday, March 18, 2025
*Seminar Day*


//end::Assignment-142[]
//tag::Assignment-143[]
===== Wednesday, March 19, 2025

Finish
https://drive.google.com/file/d/1R5f-vstdJNHc34THTplN4hk9lFHjVjI6/view?usp=sharing[Lesson 24 Homework]

Study 
https://drive.google.com/file/d/1Lpo1wNDxa9Uy-7ax98dHQzeNFsbhFlXj/view?usp=sharing[Lesson 24 Vocabulary]

//end::Assignment-143[]
//tag::Assignment-144[]
===== Thursday, March 20, 2025
Submit the rest of 
https://drive.google.com/file/d/1R5f-vstdJNHc34THTplN4hk9lFHjVjI6/view?usp=sharing[Lesson 24 Homework]

Study 
https://drive.google.com/file/d/1Lpo1wNDxa9Uy-7ax98dHQzeNFsbhFlXj/view?usp=sharing[Lesson 24 Vocabulary]


//end::Assignment-144[]
//tag::Assignment-145[]
===== Friday, March 21, 2025

//end::Assignment-145[]
//tag::Quiz-22[]

Quiz over chapter 24.

//end::Quiz-22[]
//end::Week-33[]

==== Week 34
//tag::Week-34[]
//tag::Weekly-Overview-34[]
34

//end::Weekly-Overview-34[]

//tag::Assignment-146[]
===== Monday, March 24, 2025

Submit the first two pages of
https://drive.google.com/file/d/1tmPj25cN7Gjl1iCBMEq_AuqUB_R46U79/view?usp=sharing[Chapter 25 Homework]

Study https://drive.google.com/file/d/1trY1MuSpU-SdNV72UPMyM9MExsfDH1y9/view?usp=sharing[Chapter 25 Vocabulary]

//end::Assignment-146[]
//tag::Assignment-147[]
===== Tuesday, March 25, 2025

//end::Assignment-147[]
//tag::Assignment-148[]
===== Wednesday, March 26, 2025

Finish the rest of
https://drive.google.com/file/d/1tmPj25cN7Gjl1iCBMEq_AuqUB_R46U79/view?usp=sharing[Chapter 25 Homework]

Study https://drive.google.com/file/d/1trY1MuSpU-SdNV72UPMyM9MExsfDH1y9/view?usp=sharing[Chapter 25 Vocabulary]


//end::Assignment-148[]
//tag::Assignment-149[]
===== Thursday, March 27, 2025

Submit the rest of
https://drive.google.com/file/d/1tmPj25cN7Gjl1iCBMEq_AuqUB_R46U79/view?usp=sharing[Chapter 25 Homework]

Study https://drive.google.com/file/d/1trY1MuSpU-SdNV72UPMyM9MExsfDH1y9/view?usp=sharing[Chapter 25 Vocabulary]


//end::Assignment-149[]
//tag::Assignment-150[]
===== Friday, March 28, 2025

//end::Assignment-150[]
//tag::Quiz-23[]

Quiz over chapter 25

//end::Quiz-23[]
//end::Week-34[]




==== Week 35
//tag::Week-35[]
//tag::Weekly-Overview-35[]
35

//end::Weekly-Overview-35[]

//tag::Assignment-151[]
===== Monday, March 31, 2025

Submit the first two pages of
https://drive.google.com/file/d/1A2X92PBa5dKBKpgum7zrn82ZEJXj-M5f/view?usp=sharing[Chapter 26 Homework]

Study 
https://drive.google.com/file/d/1ZECsDc8EBBMqAXVELVHFQn27u2EX43Ro/view?usp=sharing[Chapter 26 Vocabulary]

//end::Assignment-151[]
//tag::Assignment-152[]
===== Tuesday, April 1, 2025

//end::Assignment-152[]
//tag::Assignment-153[]
===== Wednesday, April 2, 2025

Complete the rest of
https://drive.google.com/file/d/1A2X92PBa5dKBKpgum7zrn82ZEJXj-M5f/view?usp=sharing[Chapter 26 Homework]

Study 
https://drive.google.com/file/d/1ZECsDc8EBBMqAXVELVHFQn27u2EX43Ro/view?usp=sharing[Chapter 26 Vocabulary]

//end::Assignment-153[]
//tag::Assignment-154[]
===== Thursday, April 3, 2025

Submit the rest of
https://drive.google.com/file/d/1A2X92PBa5dKBKpgum7zrn82ZEJXj-M5f/view?usp=sharing[Chapter 26 Homework]

Study 
https://drive.google.com/file/d/1ZECsDc8EBBMqAXVELVHFQn27u2EX43Ro/view?usp=sharing[Chapter 26 Vocabulary]

//end::Assignment-154[]
//tag::Assignment-155[]
===== Friday, April 4, 2025

//end::Assignment-155[]

//tag::Quiz-24[]

Quiz over chapter 26

//end::Quiz-24[]
//tag::Test-07[]
Test 7

//end::Test-07[]
//end::Week-35[]

=== Module 8 -- Chapter 39

==== Week 36
//tag::Week-36[]
//tag::Weekly-Overview-36[]
36

//end::Weekly-Overview-36[]
Sping Break

//end::Week-36[]

==== Week 37
//tag::Week-37[]
//tag::Weekly-Overview-37[]
37

//end::Weekly-Overview-37[]
//tag::Assignment-156[]
===== Monday, April 14, 2025

//Review 23-25

Submit
//https://drive.google.com/file/d/1RFKf5f8K2BrVrPbjgubasC9ueLaUAgTs/view?usp=sharing[Chapter 23 Story]


//end::Assignment-156[]
//tag::Assignment-157[]
===== Tuesday, April 15, 2025

*Seminar Day*

//end::Assignment-157[]
//tag::Assignment-158[]
===== Wednesday, April 16, 2025

Complete

//https://drive.google.com/file/d/1R7vnIPcBHJC6OPj4t-zgHELCtifLKUA5/view?usp=sharing[Chapter 24 Story] and

//https://drive.google.com/file/d/1usN2Fyy2r4z2JQZoGIUfKe9CfBeqqHrc/view?usp=sharing[Chapter 25 Story]


//end::Assignment-158[]
//tag::Assignment-159[]
===== Thursday, April 17, 2025

Submit

//https://drive.google.com/file/d/1R7vnIPcBHJC6OPj4t-zgHELCtifLKUA5/view?usp=sharing[Chapter 24 Story] and

//https://drive.google.com/file/d/1usN2Fyy2r4z2JQZoGIUfKe9CfBeqqHrc/view?usp=sharing[Chapter 25 Story]


//end::Assignment-159[]
//tag::Assignment-160[]
===== Friday, April 18, 2025

*Good Friday*

//end::Assignment-160[]

//end::Week-37[]

==== Week 38
//tag::Week-38[]
//tag::Weekly-Overview-38[]
38

//end::Weekly-Overview-38[]

//tag::Assignment-161[]
===== Monday, April 21, 2025

//Translate and submit Loci Antiqui II on page 352.

//end::Assignment-161[]
//tag::Assignment-162[]
===== Tuesday, April 22, 2025

//Translate Loci Antiqui III on pages 352-353.

//end::Assignment-162[]
//tag::Assignment-163[]
===== Wednesday, April 23, 2025

//Translate Loci Antiqui IV on page 353.

//end::Assignment-163[]
//tag::Assignment-164[]
===== Thursday, April 24, 2025

//Translate Loci Antiqui V on page 354.

//Submit Loci Antiqui III, IV, and V

//end::Assignment-164[]
//tag::Assignment-165[]
===== Friday, April 25, 2025

//Translate Loci Antiqui VI on pages 354-355.

//end::Assignment-165[]
//tag::Quiz-25[]

Review Quiz

//end::Quiz-25[]
//end::Week-38[]

==== Week 39
//tag::Week-39[]
//tag::Weekly-Overview-39[]
39

//end::Weekly-Overview-39[]

//tag::Assignment-166[]
===== Monday, April 28, 2025

//Finish translating and submit Loci Antiqui VI on pages 354-355.


//end::Assignment-166[]
//tag::Assignment-167[]
===== Tuesday, April 29, 2025

*Chapel Day*

//Translate Loci Antiqui VII on pages 355-356.

//end::Assignment-167[]
//tag::Assignment-168[]
===== Wednesday, April 30, 2025

//Translate Loci Antiqui VIII on pages 356-357.

//end::Assignment-168[]
//tag::Assignment-169[]
===== Thursday, May 1, 2025

//end::Assignment-169[]
//tag::Assignment-170[]
===== Friday, May 2, 2025

//Translate Loci Antiqui IX on pages 357-358.


//end::Assignment-170[]
//tag::Quiz-26[]

Review Quiz

//end::Quiz-26[]
//end::Week-39[]


==== Week 40
//tag::Week-40[]
//tag::Weekly-Overview-40[]
40

//end::Weekly-Overview-40[]

//tag::Assignment-171[]
===== Monday, May 5, 2025

//Finish and submit Loci Antiqui IX

//end::Assignment-171[]
//tag::Assignment-172[]
===== Tuesday, May 6, 2025
*Last full day in class*

//end::Assignment-172[]
//tag::Assignment-173[]
===== Wednesday, May 7, 2025

//end::Assignment-173[]
//tag::Assignment-174[]
===== Thursday, May 8, 2025

//end::Assignment-174[]
//tag::Assignment-175[]
===== Friday, May 9, 2025
*1/2 day of testing*

//end::Assignment-175[]

//tag::Test-08[]

Final

//end::Test-08[]



//tag::Quiz-27[]
Quiz 27

//end::Quiz-27[]
//end::Week-40[]













==== Week 41
//tag::Week-41[]
//tag::Weekly-Overview-41[]
41

//end::Weekly-Overview-41[]

//tag::Assignment-176[]
===== Monday, May 12, 2025

//end::Assignment-176[]
//tag::Assignment-177[]
===== Tuesday, May 13, 2025
*1/2 day of testing*

*Final Day of School*

//end::Assignment-177[]



//tag::Assignment-178[]
===== Wednesday, May 14, 2025

//end::Assignment-178[]
//tag::Assignment-179[]
===== Thursday, May 15, 2025

//end::Assignment-179[]
//tag::Assignment-180[]
===== Friday, May 16, 2025

*Teacher work day*

//end::Assignment-180[]

//end::Week-41[]







